// Location presets for the popup: city / IANA timezone / approximate coordinates.
// Pick the region your endpoint exits in so every location signal matches.
const LOCATION_PRESETS = [
  { city: "New York", country: "United States", tzId: "America/New_York", lat: 40.71, lng: -74.01 },
  { city: "Los Angeles", country: "United States", tzId: "America/Los_Angeles", lat: 34.05, lng: -118.24 },
  { city: "Chicago", country: "United States", tzId: "America/Chicago", lat: 41.88, lng: -87.63 },
  { city: "Denver", country: "United States", tzId: "America/Denver", lat: 39.74, lng: -104.99 },
  { city: "Anchorage", country: "United States", tzId: "America/Anchorage", lat: 61.22, lng: -149.9 },
  { city: "Honolulu", country: "United States", tzId: "Pacific/Honolulu", lat: 21.31, lng: -157.86 },
  { city: "Vancouver", country: "Canada", tzId: "America/Vancouver", lat: 49.28, lng: -123.12 },
  { city: "Mexico City", country: "Mexico", tzId: "America/Mexico_City", lat: 19.43, lng: -99.13 },
  { city: "Sao Paulo", country: "Brazil", tzId: "America/Sao_Paulo", lat: -23.55, lng: -46.63 },
  { city: "Buenos Aires", country: "Argentina", tzId: "America/Argentina/Buenos_Aires", lat: -34.6, lng: -58.38 },
  { city: "London", country: "United Kingdom", tzId: "Europe/London", lat: 51.51, lng: -0.13 },
  { city: "Paris", country: "France", tzId: "Europe/Paris", lat: 48.86, lng: 2.35 },
  { city: "Berlin", country: "Germany", tzId: "Europe/Berlin", lat: 52.52, lng: 13.41 },
  { city: "Madrid", country: "Spain", tzId: "Europe/Madrid", lat: 40.42, lng: -3.7 },
  { city: "Rome", country: "Italy", tzId: "Europe/Rome", lat: 41.9, lng: 12.5 },
  { city: "Amsterdam", country: "Netherlands", tzId: "Europe/Amsterdam", lat: 52.37, lng: 4.9 },
  { city: "Stockholm", country: "Sweden", tzId: "Europe/Stockholm", lat: 59.33, lng: 18.07 },
  { city: "Athens", country: "Greece", tzId: "Europe/Athens", lat: 37.98, lng: 23.73 },
  { city: "Moscow", country: "Russia", tzId: "Europe/Moscow", lat: 55.76, lng: 37.62 },
  { city: "Istanbul", country: "Turkey", tzId: "Europe/Istanbul", lat: 41.01, lng: 28.98 },
  { city: "Johannesburg", country: "South Africa", tzId: "Africa/Johannesburg", lat: -26.2, lng: 28.05 },
  { city: "Lagos", country: "Nigeria", tzId: "Africa/Lagos", lat: 6.52, lng: 3.38 },
  { city: "Nairobi", country: "Kenya", tzId: "Africa/Nairobi", lat: -1.29, lng: 36.82 },
  { city: "Dubai", country: "United Arab Emirates", tzId: "Asia/Dubai", lat: 25.2, lng: 55.27 },
  { city: "Mumbai", country: "India", tzId: "Asia/Kolkata", lat: 19.08, lng: 72.88 },
  { city: "Dhaka", country: "Bangladesh", tzId: "Asia/Dhaka", lat: 23.81, lng: 90.41 },
  { city: "Bangkok", country: "Thailand", tzId: "Asia/Bangkok", lat: 13.76, lng: 100.5 },
  { city: "Singapore", country: "Singapore", tzId: "Asia/Singapore", lat: 1.35, lng: 103.82 },
  { city: "Hong Kong", country: "Hong Kong", tzId: "Asia/Hong_Kong", lat: 22.32, lng: 114.17 },
  { city: "Beijing", country: "China", tzId: "Asia/Shanghai", lat: 39.9, lng: 116.41 },
  { city: "Shanghai", country: "China", tzId: "Asia/Shanghai", lat: 31.23, lng: 121.47 },
  { city: "Seoul", country: "South Korea", tzId: "Asia/Seoul", lat: 37.57, lng: 126.98 },
  { city: "Tokyo", country: "Japan", tzId: "Asia/Tokyo", lat: 35.68, lng: 139.65 },
  { city: "Sydney", country: "Australia", tzId: "Australia/Sydney", lat: -33.87, lng: 151.21 },
  { city: "Melbourne", country: "Australia", tzId: "Australia/Melbourne", lat: -37.81, lng: 144.96 },
  { city: "Perth", country: "Australia", tzId: "Australia/Perth", lat: -31.95, lng: 115.86 },
  { city: "Auckland", country: "New Zealand", tzId: "Pacific/Auckland", lat: -36.85, lng: 174.76 },
];

function findPreset(tzId) {
  return LOCATION_PRESETS.find(p => p.tzId === tzId);
}